# Static analysis configuration for Dart/Flutter
# More info: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Flutter best practices
    prefer_const_constructors: true # Mümkünse const constructor kullan
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true # Widgetlarda key ekle
    sort_child_properties_last: true

    # Kod okunabilirliği
    prefer_single_quotes: true # Tek tırnak kullan
    unnecessary_this: true # Gereksiz this kullanma
    avoid_unnecessary_containers: true # Boş container yerine alternatif kullan
    avoid_unused_constructor_parameters: true # Kullanılmayan parametreleri kaldır

    # Güvenlik ve maintainability
    avoid_print: true # print yerine logger kullan
    always_use_package_imports: true # Relative import yerine package: kullan
    prefer_final_fields: true # Değişmeyen alanları final yap
    prefer_final_locals: true # Değişmeyen local değişkenleri final yap

    # Daha güçlü tip kontrolü
    always_declare_return_types: true # Fonksiyonlara her zaman dönüş tipi yaz
    avoid_dynamic_calls: true # dynamic çağrılardan kaçın
    type_annotate_public_apis: true # Public API'lerde tipleri açık yaz
    avoid_empty_else: true # Boş else bloklarından kaçın
    avoid_init_to_null: true # null ile initialize etme
    prefer_typing_uninitialized_variables: true # Tipi belli olmayan değişkenleri dynamic yapma
